# Deploy Ceph Cluster

- name: ROOK - Create ceph cluster namespace
  k8s:
    name: "{{ rook_cluster_namespace }}"
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    api_version: v1
    kind: Namespace
    state: present

- name: ROOK - Define RBAC and Create the ceph cluster
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0 or result.status != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ lookup('template', 'cluster.yaml.j2') | from_yaml_all | list }}"

- name: ROOK - Deploy Ceph toolbox
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'toolbox.yaml.j2') | from_yaml }}"

- name: ROOK - Verify the cluster deploy is complete
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    api_version: ceph.rook.io/v1
    kind: CephCluster
    name: rook-ceph
    namespace: "{{ rook_cluster_namespace }}"
  register: cluster_data
  until: cluster_data.result.get('status', {}).get('state') == "Created"
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  ignore_errors: yes
