# Deploy Ceph Cluster

- name: ROOK - Create ceph cluster namespace
  k8s:
    name: "{{ rook_cluster_namespace }}"
    kubeconfig: "{{ kubeconfig_file_path }}"
    api_version: v1
    kind: Namespace
    state: present

- name: ROOK - Define RBAC Service Account for the ceph cluster namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'cluster/ceph_cluster_sa.yaml') | from_yaml }}"

- name: ROOK - Define RBAC Role for the ceph cluster namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'cluster/ceph_cluster_role.yaml') | from_yaml }}"

- name: ROOK - Define RBAC Cluster Role Binding for the ceph cluster namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'cluster/ceph_cluster_crb.yaml') | from_yaml }}"

- name: ROOK - Define RBAC Role Binding for the ceph cluster namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'cluster/ceph_cluster_role_binding.yaml') | from_yaml }}"

- name: ROOK - Create the ceph cluster
  k8s:
    kubeconfig: "{{ kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'cluster/ceph_cluster.yaml') | from_yaml }}"
