# Create storage classes as defined on variables

- name: ROOK - Create Rook Shared Filesystem
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'storages/filesystem.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0 or result.status != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ ceph_filesystems }}"
  tags: storage_creation
