# Initialize rook operator

- name: ROOK - Create operator namespace
  k8s:
    name: "{{ rook_operator_namespace }}"
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    api_version: v1
    kind: Namespace
    state: present

# Define rook custom resources

- name: ROOK - Define CustomResources
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  until: result.failed == 0 or result.status != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop:
    - "{{ lookup('file', 'operator/cluster_crd.yaml') | from_yaml }}"
    - "{{ lookup('file', 'operator/filesystem_crd.yaml') | from_yaml }}"
    - "{{ lookup('file', 'operator/object_store_crd.yaml') | from_yaml }}"
    - "{{ lookup('file', 'operator/object_store_users_crd.yaml') | from_yaml }}"
    - "{{ lookup('file', 'operator/block_pool_crd.yaml') | from_yaml }}"
    - "{{ lookup('file', 'operator/volume_crd.yaml') | from_yaml }}"

# Define RBAC roles

- name: ROOK - Define RBAC for the operator
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ item }}"
  register: result
  when: rook_kubernetes_rbac_enabled
  until: result.failed == 0 or result.status != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop:
  - "{{ lookup('file', 'operator/cluster_mgmt_rbac_cr.yaml') | from_yaml }}"
  - "{{ lookup('template', 'operator/ceph_system_role.yaml.j2') | from_yaml }}"
  - "{{ lookup('file', 'operator/rook_global_rbac_cr.yaml') | from_yaml }}"
  - "{{ lookup('file', 'operator/rook_ceph_mgr_rbac_cr.yaml') | from_yaml }}"
  - "{{ lookup('template', 'operator/ceph_system_sa.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'operator/ceph_system_role_binding.yaml.j2') | from_yaml }}"
  - "{{ lookup('template', 'operator/ceph_system_crb.yaml.j2') | from_yaml }}"

# Deployment of the rook operator

- name: ROOK - Create the Rook Operator Deployment on the operator namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'operator/rook_operator.yaml.j2') | from_yaml }}"

# Verify the deployment is completed

- name: ROOK - Verify if the rook operator is up and running
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    api_version: apps/v1beta1
    kind: Deployment
    name: rook-ceph-operator
    namespace: "{{ rook_operator_namespace }}"
  register: deployment_data
  until: deployment_data.result.status.conditions[0].status == "True"
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"

- name: ROOK - Verify if the agents are running
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    api_version: extensions/v1beta1
    kind: DaemonSet
    name: rook-ceph-agent
    namespace: "{{ rook_operator_namespace }}"
  register: daemonset_data
  until: daemonset_data.result.status.desiredNumberScheduled == daemonset_data.result.status.numberReady
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
