# Create storage classes as defined on variables

- name: Rook - Make directory to hold temp files
  file: 
    path: "/root/ansible_rook_role/storages"
    state: directory

- name: Rook - Create storage-class.yaml file from template
  template: 
     src: storages/storage-class.yaml.j2
     dest: "/root/ansible_rook_role/storages/{{item.name}}-storage-class.yaml"
  loop: "{{ rook_storage_classes }}"

- name: ROOK - Create K8s Storage Classes
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    src: "/root/ansible_rook_role/storages/{{ item.name }}-storage-class.yaml"
  register: ret
  until: not ret.failed or ret.get('rc') != 0 or ret.get('status') != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ rook_storage_classes }}"
  tags:
  - storage_creation
  - class_creation
